name = "mammoth_gray_whippet-09b3"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "mammoth_gray_whippet-09b3_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "mammoth_gray_whippet-09b3.wasm"
command = "npm run build:release"
